# Generated by Django 3.0.3 on 2020-05-06 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='owner',
            new_name='user',
        ),
    ]
